export const EVENT_TYPE = {
  MIC: "MIC",
  WEBCAM: "WEBCAM",
  ERROR: "ERROR",
  SCREEN_SHARE: "SCREEN_SHARE",
  SCREEN_SHARE_AUDIO: "SCREEN_SHARE_AUDIO",
};

export const EVENT_TYPE_WITHOUT_ERROR = {
  MIC: "MIC",
  WEBCAM: "WEBCAM",
  SCREEN_SHARE: "SCREEN_SHARE",
  SCREEN_SHARE_AUDIO: "SCREEN_SHARE_AUDIO",
};
